# CS5012 hw4 Bryce Paubel 4/10/23
# Application configuration for course-service
spring:
  application:
    name: course-service
  profiles:
    active: proj
  # Newer versions of Spring Boot use this
  config:
    import: configserver:http://configserver:8071