// CS5012 2/28/23 Bryce Paubel hw2
// Simple Student classed based off of examples

// NOTE - I had to add a lot of mapping information to the database
// because of the fact that the JPA itself was not creating the table
// For this reason, there are added column and sequence annotations

package paubel.cs5012.student;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.GenerationType;
import jakarta.persistence.SequenceGenerator;

@Entity
@Table(name = "student")
public class Student {
    // Primary key, generated by a sequence in the database
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "student_id_seq")
    @SequenceGenerator(name="student_id_seq", sequenceName = "student_id_seq", allocationSize=1)
    @Column(name = "id")
    private Long id;

    // Student's name, maps to name
    @Column(name = "name")
    private String name;

    // Student's major, maps to major
    @Column(name = "major")
    private String major;

    // Student's year, maps to year
    @Column(name = "year")
    private Integer year;

    /* Constructors */
    public Student() {
    }

    public Student(String name, String major, Integer year) {
        this.name = name;
        this.major = major;
        this.year = year;
    }

    public Student(Long id, String name, String major, Integer year) {
        this.id = id;
        this.name = name;
        this.major = major;
        this.year = year;
    }
    /* End constructors */

    /* Getters and setters */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMajor() {
        return major;
    }

    public void setMajor(String major) {
        this.major = major;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }
    /* End getters and setters */
}
