// CS5012 4/10/23 Bryce Paubel hw4
// Simple Instructor model class

// NOTE - I had to add a lot of mapping information to the database
// because of the fact that the JPA itself was not creating the table
// For this reason, there are added column and sequence annotations

package paubel.cs5012.instructor;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

@Entity
@Table(name = "instructor")
public class Instructor {
    // Primary key, generated by a sequence in the database
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "instructor_id_seq")
    @SequenceGenerator(name="instructor_id_seq", sequenceName = "instructor_id_seq", allocationSize=1)
    @Column(name = "id")
    private Long id;

    // Instructor's name, maps to name
    @Column(name = "name")
    private String name;

    // Instructor's office, maps to office
    @Column(name = "office")
    private String office;

    // Instructor's phone, maps to phone
    @Column(name = "phone")
    private String phone;

    // Instructor's email, maps to email
    @Column(name = "email")
    private String email;

    /* Constructors */
    public Instructor() {
    }

    public Instructor(String name, String office, String phone, String email) {
        this.name = name;
        this.office = office;
        this.phone = phone;
        this.email = email;
    }
    /* End constructors */

    /* Getters and setters */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOffice() {
        return office;
    }

    public void setOffice(String office) {
        this.office = office;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    /* End getters and setters */
}
